Repository Max-Edelson/cse110-sp21-group16, pull requests merged in 2021-06, with the labels that each got.

#68 Create 06-02-2021_collection_team.md
  admin/meetings/06-02-2021_collection_team.md
Labels: documentation

#78 Future log backend add to dev
  source/collection/Entry.js
  source/collection/Item.js
  source/collection/LocalStorage.js
  source/frontend/future_log/index.html
  source/frontend/future_log/source.js
  source/frontend/future_log/style.css
Labels: bug, enhancement

#96 Merge updated future backend to dev
  source/collection/Entry.js
  source/frontend/future_log/index.html
  source/frontend/future_log/source.js
Labels: enhancement

#98 Merge updated daily log with dev branch
  admin/meetings/06-02-2021_collection_team.md
  admin/meetings/06-08-2021_collection_team.md
  source/collection/Entry.js
  source/collection/LocalStorage.js
  source/custom_log/index.html
  source/daily_log/index.html
  source/daily_log/script.js
  source/daily_log/style.css
  source/frontend/daily_log/index.html
  source/frontend/daily_log/script.js
  source/frontend/daily_log/style.css
  source/rapid_log/index.html
  source/rapid_log/source.js
  source/rapid_log/style.css
  specs/onboard.md
Labels: enhancement

#108 Update the main branch monthly log from dev
  source/monthlylog/demo.html
  source/monthlylog/js/caleandar.js
Labels: enhancement
